name: Build blogpost

on:
  # Run on all PRs
  pull_request:
  # Run when a PR is merged into main
  push:
    branches:
      - main
  # Build when a release is published
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix environment
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@v1
        with:
          extraNixOptions: --accept-flake-config
      - name: Set up build folder
        run: |
          mkdir -p ./build/ && cp $(find src -type f ! -name ${{ github.event.repository.name }}.md) ./build/
      - name: Build blogpost
        run: just build
      - name: Create tarball
        run: |
          tar --create --verbose --file=./blogpost.tar --directory=./build .
      - name: Upload to release
        run: |
          gh release upload "${{ github.ref_name }}" ./blogpost.tar
        if: ${{ github.event_name == 'release' }}
        env:
          GH_TOKEN: ${{ github.token }}
